name: git_helper
version: 0.0.1

description: A simple command line interdace to help you out with some github commands
repository: https://github.com/Matteuus/git_helper

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_cli: ^2.2.1
  build_runner: ^2.3.3
  build_verify: ^3.1.0
  lints: ^2.0.0
  test: ^1.16.0
  test_process: ^2.0.3
dependencies:
  args: ^2.3.2
  build_cli_annotations: ^2.1.0
  hive: ^2.2.3
  interact: ^2.1.1
  path: ^1.8.3

executables: 
  git_helper: 

platforms:
  linux:
  macos: 
